---

- hosts: localhost

  vars_files:
    - clouds.yaml

  tasks:

  - name: release the floating ip
    os_floating_ip:
      cloud: tacc
      state: absent
      purge: yes 
      server: "{{ item }}"
    loop: "{{ compute_instance_list }}"
    register: "os_hosts"

  - debug:
      var: os_hosts

  - name: destroy the node
    os_server:
      state: absent
      name: "{{ item }}"
      cloud: tacc
      key_name: jetstream_key
      timeout: 200 
      auto_ip: yes 
      network: "{{ network_name }}"
    loop: "{{ compute_instance_list }}"
    delay: 5
    retries: 3

#    shell: sudo kill -s 9 $(ps aux | grep ssh | awk '/{{ item }}/ {print $2}' | tr '\n' ' ')

  - name: kill the ssh tunnel
    shell: kill -s 9 $(ps aux | grep ssh | awk '/{{ item }}/ {print $2}' | tr '\n' ' ')
    loop: "{{ compute_instance_list }}"
    ignore_errors: yes

  - name: remove hosts from etc/hosts  - TEST
    lineinfile:
      regexp: "{{ item }}"
      state: absent
      path: /etc/hosts
    loop: "{{ compute_instance_list }}"
