---

- hosts: localhost

  vars_files:
    - clouds.yaml

  tasks:

  - name: release the floating ip
    os_floating_ip:
      cloud: tacc
      state: absent
      purge: yes 
      server: "{{ item }}"
    loop: "{{ compute_instance_list }}"

  - name: destroy the node
    os_server:
      state: absent
      name: "{{ item }}"
      cloud: tacc
      key_name: jetstream_key
      timeout: 200 
      auto_ip: yes 
      network: "{{ network_name }}"
    loop: "{{ compute_instance_list }}"
    register: "os_hosts"
    delay: 5

  - name: remove hosts from etc/hosts  - TEST
    lineinfile:
      line: "{{ item.openstack.accessIPv4 }} {{ item['openstack']['name'] }}"
      state: absent
      path: /etc/hosts
    with_items: "{{ os_hosts.results }}"
